export const graphicCategories = [
  {
    id: 'logo-identity',
    name: 'Logo & Identity',
    slug: 'logo-identity-design',
    description: 'Establish a powerful brand identity with custom logos, business cards, letterheads, and corporate stationery.',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=1504x1127&vertical=center',
    badge: 'Popular',
    color: 'from-violet-500 to-indigo-600',
    accent: '#5348e2',
  },
  {
    id: 'graphic-design',
    name: 'Graphic Design',
    slug: 'graphic-design',
    description: 'Transform concepts into visual masterpieces with vector artwork, 3D modeling, infographics, and podcast visuals.',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=1504x1177&vertical=center',
    badge: 'Trending',
    color: 'from-blue-500 to-cyan-600',
    accent: '#0284c7',
  },
  {
    id: 'web-design',
    name: 'Web Design',
    slug: 'web-design',
    description: 'Conversion-driven UI/UX design for websites, WordPress, Shopify, landing pages, and mobile applications.',
    image: 'https://cdn.dribbble.com/userupload/41515672/file/original-d7b0d58ba561acc5f345b261493db68b.png?resize=1504x1128&vertical=center',
    badge: 'High ROI',
    color: 'from-emerald-500 to-teal-600',
    accent: '#059669',
  },
  {
    id: 'digital-marketing',
    name: 'Digital Marketing',
    slug: 'digital-marketing',
    description: 'Scroll-stopping banner ads, social media creatives, newsletters, and email templates crafted to engage your audience.',
    image: 'https://cdn.dribbble.com/userupload/27119923/file/original-c3c1a4ce8d1792261d73e97127530ec6.png?resize=1504x1128&vertical=center',
    badge: 'New',
    color: 'from-orange-500 to-amber-600',
    accent: '#ea580c',
  },
  {
    id: 'outdoor-signage',
    name: 'Outdoor & Signage',
    slug: 'outdoor-signage',
    description: 'Command attention outdoors with high-impact billboards, trade show booths, vehicle car wraps, and storefront signs.',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=1504x1203&vertical=center',
    badge: 'High Impact',
    color: 'from-rose-500 to-red-600',
    accent: '#e11d48',
  },
  {
    id: 'print-design',
    name: 'Print Design',
    slug: 'print-design',
    description: 'Tactile marketing excellence including flyers, brochures, posters, menus, catalogues, and invitation designs.',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=1504x1203&vertical=center',
    badge: 'Best Seller',
    color: 'from-fuchsia-500 to-pink-600',
    accent: '#c026d3',
  },
  {
    id: 'product-merchandize',
    name: 'Product & Merchandize',
    slug: 'Product-Merchandize',
    description: 'Custom apparel, custom t-shirt designs, packaging, product labels, and promotional merchandise that people love.',
    image: 'https://cdn.dribbble.com/userupload/46205579/file/2f3e2f7e3469ad598ba64c4bacc0133a.jpg?resize=1504x1128&vertical=center',
    badge: 'Custom',
    color: 'from-amber-500 to-yellow-600',
    accent: '#d97706',
  },
  {
    id: 'art-illustration',
    name: 'Art & Illustration',
    slug: 'Art-Illustration',
    description: 'Unique custom illustrations, book covers, brand mascots, custom characters, and tattoo artwork by expert artists.',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=1504x1128&vertical=center',
    badge: 'Creative',
    color: 'from-purple-500 to-indigo-600',
    accent: '#9333ea',
  },
];

export const graphicServicesList = [
  // 1. Logo & Identity
  {
    id: 'logo-design',
    name: 'Logo Design',
    categorySlug: 'logo-identity-design',
    categoryName: 'Logo & Identity',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹2,499',
    turnaround: '24-48 Hours',
    rating: 4.9,
    reviews: 284,
    badge: 'Best Seller',
    desc: 'Bespoke, unforgettable logo design tailored to embody your brand mission across print and digital.',
    deliverables: ['Vector AI / EPS', 'Transparent PNG', 'High-Res JPG', 'Brand Guidelines']
  },
  {
    id: 'business-card-design',
    name: 'Business Card Design',
    categorySlug: 'logo-identity-design',
    categoryName: 'Logo & Identity',
    image: 'https://cdn.dribbble.com/userupload/41515672/file/original-d7b0d58ba561acc5f345b261493db68b.png?resize=800x600&vertical=center',
    price: '₹999',
    turnaround: '24 Hours',
    rating: 4.8,
    reviews: 195,
    badge: 'Popular',
    desc: 'Professional double-sided business card designs optimized for print with QR codes and spot UV readiness.',
    deliverables: ['Print-Ready CMYK PDF', 'Source AI/PSD', 'Bleed & Crop Marks']
  },
  {
    id: 'stationery-design',
    name: 'Stationery Design',
    categorySlug: 'logo-identity-design',
    categoryName: 'Logo & Identity',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=800x600&vertical=center',
    price: '₹2,999',
    turnaround: '2-3 Days',
    rating: 4.9,
    reviews: 132,
    desc: 'Complete corporate stationery kit including letterhead, envelopes, presentation folders, and notepad templates.',
    deliverables: ['Full Stationery Suite', 'Print-Ready PDF', 'Editable Word DOCX']
  },
  {
    id: 'letterhead-design',
    name: 'Letterhead Design',
    categorySlug: 'logo-identity-design',
    categoryName: 'Logo & Identity',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=800x600&vertical=center',
    price: '₹799',
    turnaround: '24 Hours',
    rating: 4.8,
    reviews: 89,
    desc: 'Sleek executive letterhead layouts ready for official business correspondence and digital invoices.',
    deliverables: ['MS Word Template', 'Print PDF', 'Source Vector File']
  },
  {
    id: 'envelope-design',
    name: 'Envelope Design',
    categorySlug: 'logo-identity-design',
    categoryName: 'Logo & Identity',
    image: 'https://cdn.dribbble.com/userupload/27119923/file/original-c3c1a4ce8d1792261d73e97127530ec6.png?resize=800x600&vertical=center',
    price: '₹699',
    turnaround: '24 Hours',
    rating: 4.7,
    reviews: 64,
    desc: 'Branded standard and window envelopes that impress before the letter is even opened.',
    deliverables: ['Print-ready Die Lines', 'CMYK PDF', 'Vector AI']
  },
  {
    id: 'powerpoint-design',
    name: 'PowerPoint Design',
    categorySlug: 'logo-identity-design',
    categoryName: 'Logo & Identity',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹3,499',
    turnaround: '2-4 Days',
    rating: 4.9,
    reviews: 147,
    badge: 'Pro',
    desc: 'High-converting investor pitch decks and corporate slides with custom diagrams, icons, and master layouts.',
    deliverables: ['Editable PPTX File', 'Custom Master Slide', 'Icon Library Included']
  },
  {
    id: 'word-doc-design',
    name: 'Word Doc Design',
    categorySlug: 'logo-identity-design',
    categoryName: 'Logo & Identity',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹1,299',
    turnaround: '24-48 Hours',
    rating: 4.8,
    reviews: 78,
    desc: 'Polished Microsoft Word reports, whitepapers, proposals, and corporate documents with clean typography.',
    deliverables: ['Editable MS Word DOCX', 'Custom Styles Setup', 'PDF Export']
  },

  // 2. Graphic Design
  {
    id: 'custom-graphic-design',
    name: 'Graphic Design',
    categorySlug: 'graphic-design',
    categoryName: 'Graphic Design',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=800x600&vertical=center',
    price: '₹1,999',
    turnaround: '24-48 Hours',
    rating: 4.9,
    reviews: 310,
    badge: 'Popular',
    desc: 'All-purpose custom visual design for digital campaigns, brand graphics, and creative marketing collateral.',
    deliverables: ['High-Res Vector', 'PSD / AI Source', 'Commercial Usage Rights']
  },
  {
    id: 'infographic-design',
    name: 'Infographic Design',
    categorySlug: 'graphic-design',
    categoryName: 'Graphic Design',
    image: 'https://cdn.dribbble.com/userupload/41515672/file/original-d7b0d58ba561acc5f345b261493db68b.png?resize=800x600&vertical=center',
    price: '₹2,799',
    turnaround: '2-3 Days',
    rating: 4.9,
    reviews: 165,
    desc: 'Convert complex statistics and workflows into visually engaging, data-rich infographics.',
    deliverables: ['Vector Infographic', 'High-Res PNG & PDF', 'Editable Charts']
  },
  {
    id: '3d-design',
    name: '3D Design',
    categorySlug: 'graphic-design',
    categoryName: 'Graphic Design',
    image: 'https://cdn.dribbble.com/userupload/46205579/file/2f3e2f7e3469ad598ba64c4bacc0133a.jpg?resize=800x600&vertical=center',
    price: '₹5,999',
    turnaround: '3-5 Days',
    rating: 5.0,
    reviews: 94,
    badge: 'Premium',
    desc: 'Photorealistic 3D product mockups, architectural renders, and isometric 3D graphic elements.',
    deliverables: ['3D Source (.OBJ/.FBX)', '4K Rendered PNGs', 'Lighting & Textures']
  },
  {
    id: 'photoshop-design',
    name: 'Photoshop Design',
    categorySlug: 'graphic-design',
    categoryName: 'Graphic Design',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=800x600&vertical=center',
    price: '₹999',
    turnaround: '24 Hours',
    rating: 4.8,
    reviews: 218,
    desc: 'Expert photo manipulation, high-end retouching, color grading, background removal, and digital collages.',
    deliverables: ['Layered PSD Source', 'Web & Print Export']
  },
  {
    id: 'vector-design',
    name: 'Vector Design',
    categorySlug: 'graphic-design',
    categoryName: 'Graphic Design',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹1,499',
    turnaround: '24 Hours',
    rating: 4.9,
    reviews: 142,
    desc: 'Precision raster-to-vector tracing and scalable vector artwork suitable for any print resolution.',
    deliverables: ['AI / EPS / SVG Files', '100% Scalable Vectors']
  },
  {
    id: 'icon-design',
    name: 'Icon Design',
    categorySlug: 'graphic-design',
    categoryName: 'Graphic Design',
    image: 'https://cdn.dribbble.com/userupload/27119923/file/original-c3c1a4ce8d1792261d73e97127530ec6.png?resize=800x600&vertical=center',
    price: '₹1,799',
    turnaround: '24-48 Hours',
    rating: 4.8,
    reviews: 111,
    desc: 'Custom icon sets designed with consistent line weight and visual metaphor for websites and apps.',
    deliverables: ['SVG Icon Set', 'Figma / AI Component Library']
  },
  {
    id: 'ad-design',
    name: 'Ad Design',
    categorySlug: 'graphic-design',
    categoryName: 'Graphic Design',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹1,499',
    turnaround: '24 Hours',
    rating: 4.9,
    reviews: 201,
    badge: 'High ROI',
    desc: 'Striking promotional graphics and ad creatives optimized for digital platforms and print publications.',
    deliverables: ['Multi-size Formats', 'High-Res Ready']
  },
  {
    id: 'podcast-design',
    name: 'Podcast Design',
    categorySlug: 'graphic-design',
    categoryName: 'Graphic Design',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=800x600&vertical=center',
    price: '₹1,699',
    turnaround: '24-48 Hours',
    rating: 4.9,
    reviews: 86,
    desc: 'Standout podcast cover art compliant with Apple Podcasts and Spotify dimensions (3000x3000px).',
    deliverables: ['3000x3000px High-Res', 'Social Promo Kit']
  },

  // 3. Web Design
  {
    id: 'custom-web-design',
    name: 'Web Design',
    categorySlug: 'web-design',
    categoryName: 'Web Design',
    image: 'https://cdn.dribbble.com/userupload/41515672/file/original-d7b0d58ba561acc5f345b261493db68b.png?resize=800x600&vertical=center',
    price: '₹9,999',
    turnaround: '4-7 Days',
    rating: 5.0,
    reviews: 245,
    badge: 'Popular',
    desc: 'Modern, fully responsive desktop and mobile web designs with intuitive UX and high-conversion layouts.',
    deliverables: ['Figma / Adobe XD Design', 'Desktop & Mobile Screens', 'Interactive Prototype']
  },
  {
    id: 'wordpress-design',
    name: 'Wordpress Design',
    categorySlug: 'web-design',
    categoryName: 'Web Design',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹12,499',
    turnaround: '5-8 Days',
    rating: 4.9,
    reviews: 198,
    desc: 'Custom WordPress theme UI designs tailored for Elementor, Gutenberg, or custom PHP implementation.',
    deliverables: ['Custom Theme UI', 'Responsive Breakpoints', 'Style Guide']
  },
  {
    id: 'landing-page-design',
    name: 'Landing Page Design',
    categorySlug: 'web-design',
    categoryName: 'Web Design',
    image: 'https://cdn.dribbble.com/userupload/27119923/file/original-c3c1a4ce8d1792261d73e97127530ec6.png?resize=800x600&vertical=center',
    price: '₹4,999',
    turnaround: '2-3 Days',
    rating: 4.9,
    reviews: 320,
    badge: 'High Conversion',
    desc: 'Laser-focused sales and lead generation landing page designs engineered for maximum CTA conversion rates.',
    deliverables: ['Figma Source', 'Copy Layout Structure', 'Mobile Optimized']
  },
  {
    id: 'bigcommerce-design',
    name: 'BigCommerce Design',
    categorySlug: 'web-design',
    categoryName: 'Web Design',
    image: 'https://cdn.dribbble.com/userupload/46205579/file/2f3e2f7e3469ad598ba64c4bacc0133a.jpg?resize=800x600&vertical=center',
    price: '₹14,999',
    turnaround: '6-9 Days',
    rating: 4.8,
    reviews: 65,
    desc: 'Enterprise e-commerce UI design for BigCommerce storefronts with optimized checkout and catalog flows.',
    deliverables: ['Complete Storefront UX', 'Product & Cart Screens']
  },
  {
    id: 'shopify-design',
    name: 'Shopify Design',
    categorySlug: 'web-design',
    categoryName: 'Web Design',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=800x600&vertical=center',
    price: '₹11,999',
    turnaround: '5-7 Days',
    rating: 4.9,
    reviews: 212,
    badge: 'Trending',
    desc: 'High-converting Shopify store designs, custom sections, and branded product pages that elevate sales.',
    deliverables: ['Figma Shopify Theme UI', 'Mobile Commerce UX']
  },
  {
    id: 'squarespace-design',
    name: 'Squarespace Design',
    categorySlug: 'web-design',
    categoryName: 'Web Design',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹7,999',
    turnaround: '3-5 Days',
    rating: 4.8,
    reviews: 91,
    desc: 'Sleek portfolio, agency, and small business designs built for seamless Squarespace platform integration.',
    deliverables: ['Custom Layout Strategy', 'Visual Asset Pack']
  },
  {
    id: 'wix-design',
    name: 'Wix Design',
    categorySlug: 'web-design',
    categoryName: 'Web Design',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=800x600&vertical=center',
    price: '₹6,999',
    turnaround: '3-4 Days',
    rating: 4.8,
    reviews: 104,
    desc: 'Custom Wix Studio and Wix Editor web designs that combine creative freedom with rapid deployment.',
    deliverables: ['Wix Custom Layout', 'Responsive Mobile Views']
  },
  {
    id: 'app-design',
    name: 'App Design',
    categorySlug: 'web-design',
    categoryName: 'Web Design',
    image: 'https://cdn.dribbble.com/userupload/41515672/file/original-d7b0d58ba561acc5f345b261493db68b.png?resize=800x600&vertical=center',
    price: '₹14,999',
    turnaround: '6-10 Days',
    rating: 5.0,
    reviews: 178,
    badge: 'Best Seller',
    desc: 'iOS and Android native mobile application UI/UX designs with intuitive user flows and micro-interactions.',
    deliverables: ['Figma Prototype', 'Complete App Flow Screens', 'Design Tokens']
  },

  // 4. Digital Marketing
  {
    id: 'banner-ad-design',
    name: 'Banner Ad Design',
    categorySlug: 'digital-marketing',
    categoryName: 'Digital Marketing',
    image: 'https://cdn.dribbble.com/userupload/27119923/file/original-c3c1a4ce8d1792261d73e97127530ec6.png?resize=800x600&vertical=center',
    price: '₹999',
    turnaround: '24 Hours',
    rating: 4.9,
    reviews: 188,
    badge: 'Popular',
    desc: 'High CTR Google Display Network and web banner packages in all standard IAB dimensions.',
    deliverables: ['All Standard Ad Sizes', 'Web-Optimized PNG/JPG', 'Source PSD/Figma']
  },
  {
    id: 'newsletter-design',
    name: 'Newsletter Design',
    categorySlug: 'digital-marketing',
    categoryName: 'Digital Marketing',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹1,999',
    turnaround: '24-48 Hours',
    rating: 4.8,
    reviews: 142,
    desc: 'Engaging, branded digital newsletter templates designed to boost subscriber click-throughs.',
    deliverables: ['Mailchimp / Klaviyo Ready UI', 'Editable Figma/Photoshop']
  },
  {
    id: 'email-design',
    name: 'Email Design',
    categorySlug: 'digital-marketing',
    categoryName: 'Digital Marketing',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹1,799',
    turnaround: '24 Hours',
    rating: 4.9,
    reviews: 167,
    desc: 'Promotional email campaign graphics and e-commerce automated flow layouts that drive sales.',
    deliverables: ['Mobile-Responsive Email UI', 'Sliced Ready Assets']
  },
  {
    id: 'facebook-design',
    name: 'Facebook Design',
    categorySlug: 'digital-marketing',
    categoryName: 'Digital Marketing',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=800x600&vertical=center',
    price: '₹899',
    turnaround: '24 Hours',
    rating: 4.8,
    reviews: 215,
    desc: 'Facebook ad creatives, page cover photos, event banners, and carousel ad graphics.',
    deliverables: ['FB Ad Carousel Sets', 'Page Cover High-Res']
  },
  {
    id: 'twitter-design',
    name: 'Twitter Design',
    categorySlug: 'digital-marketing',
    categoryName: 'Digital Marketing',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=800x600&vertical=center',
    price: '₹799',
    turnaround: '24 Hours',
    rating: 4.7,
    reviews: 82,
    desc: 'X (Twitter) profile headers, thread graphics, and sponsored promotional post creatives.',
    deliverables: ['Profile Branding Kit', 'Post Graphic Templates']
  },
  {
    id: 'youtube-design',
    name: 'YouTube Design',
    categorySlug: 'digital-marketing',
    categoryName: 'Digital Marketing',
    image: 'https://cdn.dribbble.com/userupload/46205579/file/2f3e2f7e3469ad598ba64c4bacc0133a.jpg?resize=800x600&vertical=center',
    price: '₹1,299',
    turnaround: '24 Hours',
    rating: 5.0,
    reviews: 275,
    badge: 'Trending',
    desc: 'High-CTR YouTube video thumbnails, channel banners, end screens, and intro graphic slates.',
    deliverables: ['Click-Magnet Thumbnails', 'Channel Banner Art', 'Source Files']
  },

  // 5. Outdoor & Signage
  {
    id: 'billboard-design',
    name: 'Billboard Design',
    categorySlug: 'outdoor-signage',
    categoryName: 'Outdoor & Signage',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=800x600&vertical=center',
    price: '₹4,999',
    turnaround: '2-4 Days',
    rating: 5.0,
    reviews: 119,
    badge: 'High Impact',
    desc: 'Large-format highway billboards and digital hoardings designed for instant readability at high speeds.',
    deliverables: ['Print-Ready Vector PDF', 'Exact Physical Scale Setup', 'Color Proofing']
  },
  {
    id: 'trade-show-booth-design',
    name: 'Trade Show Booth Design',
    categorySlug: 'outdoor-signage',
    categoryName: 'Outdoor & Signage',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹7,999',
    turnaround: '3-5 Days',
    rating: 4.9,
    reviews: 84,
    desc: 'Exhibition backdrop stands, popup banners, podium graphics, and full exhibition booth wraps.',
    deliverables: ['Multi-panel Print Files', '3D Booth Preview']
  },
  {
    id: 'signage-design',
    name: 'Signage Design',
    categorySlug: 'outdoor-signage',
    categoryName: 'Outdoor & Signage',
    image: 'https://cdn.dribbble.com/userupload/41515672/file/original-d7b0d58ba561acc5f345b261493db68b.png?resize=800x600&vertical=center',
    price: '₹2,499',
    turnaround: '2-3 Days',
    rating: 4.8,
    reviews: 153,
    desc: 'Storefront shop fascias, directional wayfinding signs, acrylic boards, and glow sign box graphics.',
    deliverables: ['Vector Print Die Lines', 'Architectural Mockup']
  },
  {
    id: 'car-wrap-design',
    name: 'Car Wrap Design',
    categorySlug: 'outdoor-signage',
    categoryName: 'Outdoor & Signage',
    image: 'https://cdn.dribbble.com/userupload/46205579/file/2f3e2f7e3469ad598ba64c4bacc0133a.jpg?resize=800x600&vertical=center',
    price: '₹6,499',
    turnaround: '3-5 Days',
    rating: 4.9,
    reviews: 137,
    badge: 'Popular',
    desc: 'Full and partial vehicle wraps for cars, delivery vans, food trucks, and corporate fleet branding.',
    deliverables: ['Exact Blueprint Vehicle Scale', 'Print-Ready Vector Files', '360° Mockups']
  },

  // 6. Print Design
  {
    id: 'flyer-design',
    name: 'Flyer Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=800x600&vertical=center',
    price: '₹999',
    turnaround: '24 Hours',
    rating: 4.9,
    reviews: 380,
    badge: 'Best Seller',
    desc: 'Single or double-sided marketing flyers designed to capture attention and communicate offers clearly.',
    deliverables: ['300 DPI CMYK Print PDF', 'Source File', 'Social Media Share File']
  },
  {
    id: 'brochure-design',
    name: 'Brochure Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=800x600&vertical=center',
    price: '₹2,499',
    turnaround: '2-3 Days',
    rating: 4.9,
    reviews: 264,
    badge: 'Popular',
    desc: 'Bi-fold, tri-fold, or multi-page corporate brochure layouts crafted with visual hierarchy and precision.',
    deliverables: ['Print-Ready Fold Line PDF', 'Editable Adobe InDesign / AI']
  },
  {
    id: 'poster-design',
    name: 'Poster Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹1,499',
    turnaround: '24-48 Hours',
    rating: 4.9,
    reviews: 192,
    desc: 'Creative event posters, movie artwork, promotional posters, and wall graphics with vibrant aesthetics.',
    deliverables: ['High-Res Vector PDF', 'Any Custom Size']
  },
  {
    id: 'postcard-design',
    name: 'Postcard Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/27119923/file/original-c3c1a4ce8d1792261d73e97127530ec6.png?resize=800x600&vertical=center',
    price: '₹899',
    turnaround: '24 Hours',
    rating: 4.8,
    reviews: 110,
    desc: 'Direct mail postcards, thank-you notes, and promotional cards designed for postal mailing regulations.',
    deliverables: ['Standard Postcard Sizes', 'CMYK Ready']
  },
  {
    id: 'invitation-design',
    name: 'Invitation Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹1,299',
    turnaround: '24-48 Hours',
    rating: 4.9,
    reviews: 175,
    desc: 'Elegant wedding invitations, corporate event passes, gala invites, and digital e-invitation suites.',
    deliverables: ['Print & Digital Version', 'Custom Typography & Foil Ready']
  },
  {
    id: 'card-design',
    name: 'Card Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/41515672/file/original-d7b0d58ba561acc5f345b261493db68b.png?resize=800x600&vertical=center',
    price: '₹799',
    turnaround: '24 Hours',
    rating: 4.8,
    reviews: 94,
    desc: 'VIP membership cards, loyalty punch cards, gift vouchers, and ID badge cards.',
    deliverables: ['Print-Ready Die Line File', 'Source Vector']
  },
  {
    id: 'greeting-card-design',
    name: 'Greeting Card Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹999',
    turnaround: '24 Hours',
    rating: 4.9,
    reviews: 88,
    desc: 'Custom holiday cards, festive corporate greetings, and personalized birthday/anniversary cards.',
    deliverables: ['Folded & Flat Print Options', 'Digital E-Card File']
  },
  {
    id: 'catalogue-design',
    name: 'Catalogue Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/46205579/file/2f3e2f7e3469ad598ba64c4bacc0133a.jpg?resize=800x600&vertical=center',
    price: '₹6,999',
    turnaround: '4-7 Days',
    rating: 5.0,
    reviews: 140,
    badge: 'Pro',
    desc: 'Multi-page product catalogues, price lists, and corporate lookbooks designed for seamless reading.',
    deliverables: ['High-Res Catalog PDF', 'InDesign Packaged Files']
  },
  {
    id: 'magazine-design',
    name: 'Magazine Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=800x600&vertical=center',
    price: '₹8,999',
    turnaround: '5-8 Days',
    rating: 4.9,
    reviews: 96,
    desc: 'Editorial layouts, magazine covers, feature spread typography, and digital publication formatting.',
    deliverables: ['Print & Digital Layouts', 'Editorial Grid Master']
  },
  {
    id: 'menu-design',
    name: 'Menu Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=800x600&vertical=center',
    price: '₹1,999',
    turnaround: '2-3 Days',
    rating: 4.9,
    reviews: 210,
    badge: 'Popular',
    desc: 'Mouthwatering restaurant menus, cafe boards, bar drink menus, and QR code interactive menus.',
    deliverables: ['Print-Ready Lamination PDF', 'Digital QR Display Version']
  },
  {
    id: 'newspaper-ad-design',
    name: 'Newspaper Ad Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/27119923/file/original-c3c1a4ce8d1792261d73e97127530ec6.png?resize=800x600&vertical=center',
    price: '₹1,199',
    turnaround: '24 Hours',
    rating: 4.8,
    reviews: 73,
    desc: 'Crisp black & white or color newspaper advertisements formatted for precise publication columns.',
    deliverables: ['Publication Grade PDF', 'Correct Newspaper Bleeds']
  },
  {
    id: 'custom-print-design',
    name: 'Print Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹1,499',
    turnaround: '24-48 Hours',
    rating: 4.9,
    reviews: 130,
    desc: 'Bespoke print graphics tailored for any unique format, specialty paper, or custom printing requirement.',
    deliverables: ['Custom Print Files', 'Expert Color Profiling']
  },
  {
    id: 'sticker-design',
    name: 'Sticker Design',
    categorySlug: 'print-design',
    categoryName: 'Print Design',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹799',
    turnaround: '24 Hours',
    rating: 4.9,
    reviews: 235,
    badge: 'Trending',
    desc: 'Custom die-cut stickers, holographic decal artwork, product seals, and laptop sticker sets.',
    deliverables: ['Vector Cut-Line Path', 'Transparent SVG/PNG']
  },

  // 7. Product & Merchandize
  {
    id: 't-shirt-design',
    name: 'T-shirt Design',
    categorySlug: 'Product-Merchandize',
    categoryName: 'Product & Merchandize',
    image: 'https://cdn.dribbble.com/userupload/46205579/file/2f3e2f7e3469ad598ba64c4bacc0133a.jpg?resize=800x600&vertical=center',
    price: '₹1,499',
    turnaround: '24-48 Hours',
    rating: 5.0,
    reviews: 412,
    badge: 'Best Seller',
    desc: 'High-impact streetwear, typography, illustration, and corporate T-shirt artwork ready for screen or DTF printing.',
    deliverables: ['Transparent 300 DPI PNG', 'Vector AI/EPS', 'Realistic T-Shirt Mockup']
  },
  {
    id: 'apparel-design',
    name: 'Apparel Design',
    categorySlug: 'Product-Merchandize',
    categoryName: 'Product & Merchandize',
    image: 'https://cdn.dribbble.com/userupload/41515672/file/original-d7b0d58ba561acc5f345b261493db68b.png?resize=800x600&vertical=center',
    price: '₹2,499',
    turnaround: '2-3 Days',
    rating: 4.9,
    reviews: 184,
    desc: 'Custom hoodies, jackets, sportswear jerseys, caps, and complete uniform apparel collections.',
    deliverables: ['Apparel Pattern Vector', 'Sublimation Ready Files']
  },
  {
    id: 'merchandize-design',
    name: 'Merchandize Design',
    categorySlug: 'Product-Merchandize',
    categoryName: 'Product & Merchandize',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=800x600&vertical=center',
    price: '₹1,999',
    turnaround: '2 Days',
    rating: 4.8,
    reviews: 156,
    desc: 'Branded corporate swag items including keychains, lanyards, mousepads, coasters, and umbrellas.',
    deliverables: ['Custom Product Vectors', 'Complete Swag Pack Mockups']
  },
  {
    id: 'cup-and-mug-design',
    name: 'Cup and Mug Design',
    categorySlug: 'Product-Merchandize',
    categoryName: 'Product & Merchandize',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹799',
    turnaround: '24 Hours',
    rating: 4.9,
    reviews: 198,
    desc: 'Wraparound ceramic mug artwork, coffee paper cup branding, and tumbler engraving designs.',
    deliverables: ['Wrap-Around Print Template', 'Curved 3D Mockup']
  },
  {
    id: 'bag-and-tote-design',
    name: 'Bag and Tote Design',
    categorySlug: 'Product-Merchandize',
    categoryName: 'Product & Merchandize',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=800x600&vertical=center',
    price: '₹1,199',
    turnaround: '24-48 Hours',
    rating: 4.8,
    reviews: 114,
    desc: 'Eco-friendly canvas tote bag illustrations, retail paper shopping bags, and branded carry bags.',
    deliverables: ['Bag Screen Print File', 'Mockup Previews']
  },
  {
    id: 'label-design',
    name: 'Label Design',
    categorySlug: 'Product-Merchandize',
    categoryName: 'Product & Merchandize',
    image: 'https://cdn.dribbble.com/userupload/27119923/file/original-c3c1a4ce8d1792261d73e97127530ec6.png?resize=800x600&vertical=center',
    price: '₹2,199',
    turnaround: '2-3 Days',
    rating: 4.9,
    reviews: 240,
    badge: 'Popular',
    desc: 'Eye-catching bottle labels, jar stickers, cosmetic labels, and supplement container labels.',
    deliverables: ['Die-Cut Vector Label', 'FDA/Regulatory Compliant Grid', '3D Bottle Mockup']
  },
  {
    id: 'packaging-design',
    name: 'Packaging Design',
    categorySlug: 'Product-Merchandize',
    categoryName: 'Product & Merchandize',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹4,999',
    turnaround: '3-5 Days',
    rating: 5.0,
    reviews: 289,
    badge: 'Premium',
    desc: 'Custom product boxes, mailer boxes, pouches, and luxury packaging dielines built to shelf-standout standards.',
    deliverables: ['Complete Die-Line Blueprint', 'Print-Ready Vector', '3D Photorealistic Box Mockup']
  },

  // 8. Art & Illustration
  {
    id: 'illustration-design',
    name: 'Illustration Design',
    categorySlug: 'Art-Illustration',
    categoryName: 'Art & Illustration',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹2,999',
    turnaround: '2-4 Days',
    rating: 5.0,
    reviews: 310,
    badge: 'Popular',
    desc: 'Custom hand-drawn or digital illustrations for editorials, websites, children’s books, and brand storytelling.',
    deliverables: ['High-Res Digital Canvas', 'Layered PSD / Vector AI', 'Commercial License']
  },
  {
    id: 'book-cover-design',
    name: 'Book Cover Design',
    categorySlug: 'Art-Illustration',
    categoryName: 'Art & Illustration',
    image: 'https://cdn.dribbble.com/userupload/43836191/file/original-b8a0689eac221e7251b6d3003b9b8d4c.png?resize=800x600&vertical=center',
    price: '₹3,499',
    turnaround: '3-5 Days',
    rating: 4.9,
    reviews: 204,
    badge: 'Best Seller',
    desc: 'Bestseller-worthy paperback and hardcover book cover designs with spine and back cover layout.',
    deliverables: ['Print-Ready KDP/Offset Cover', 'Spine & Flap Calculation', '3D Book Mockup']
  },
  {
    id: 'ebook-cover-design',
    name: 'eBook Cover Design',
    categorySlug: 'Art-Illustration',
    categoryName: 'Art & Illustration',
    image: 'https://cdn.dribbble.com/userupload/41515672/file/original-d7b0d58ba561acc5f345b261493db68b.png?resize=800x600&vertical=center',
    price: '₹1,499',
    turnaround: '24-48 Hours',
    rating: 4.9,
    reviews: 168,
    desc: 'High-impact Kindle and digital eBook covers designed to pop out in small thumbnail sizes.',
    deliverables: ['Kindle Optimized JPEG', 'High-Res Digital File']
  },
  {
    id: 'cd-cover-design',
    name: 'CD Cover Design',
    categorySlug: 'Art-Illustration',
    categoryName: 'Art & Illustration',
    image: 'https://cdn.dribbble.com/userupload/46205579/file/2f3e2f7e3469ad598ba64c4bacc0133a.jpg?resize=800x600&vertical=center',
    price: '₹1,799',
    turnaround: '2 Days',
    rating: 4.8,
    reviews: 92,
    desc: 'Music album cover artwork, vinyl sleeve layouts, and Spotify/Apple Music streaming cover squares.',
    deliverables: ['3000x3000px Streaming Art', 'Print Jewel Case PDF']
  },
  {
    id: 'art-design',
    name: 'Art Design',
    categorySlug: 'Art-Illustration',
    categoryName: 'Art & Illustration',
    image: 'https://cdn.dribbble.com/userupload/46584152/file/4d07c465cf0084c269ac9af4f8cf234d.jpg?resize=800x600&vertical=center',
    price: '₹3,999',
    turnaround: '3-5 Days',
    rating: 4.9,
    reviews: 125,
    desc: 'Fine art digital prints, abstract canvas designs, gallery wall posters, and expressive artistic pieces.',
    deliverables: ['Ultra High-Res Print File', 'Museum Grade Color Profile']
  },
  {
    id: 'mascot-design',
    name: 'Mascot Design',
    categorySlug: 'Art-Illustration',
    categoryName: 'Art & Illustration',
    image: 'https://cdn.dribbble.com/userupload/42531516/file/original-c1d3716043e3a426e1e1471197fb08c5.jpg?resize=800x600&vertical=center',
    price: '₹4,499',
    turnaround: '3-5 Days',
    rating: 5.0,
    reviews: 188,
    badge: 'Pro',
    desc: 'Charismatic brand mascots, sports team characters, and esports cartoon emblems with multiple poses.',
    deliverables: ['Vector AI Character Sheet', 'Multiple Emotional Poses', 'Transparent PNG']
  },
  {
    id: 'character-design',
    name: 'Character Design',
    categorySlug: 'Art-Illustration',
    categoryName: 'Art & Illustration',
    image: 'https://cdn.dribbble.com/userupload/27119923/file/original-c3c1a4ce8d1792261d73e97127530ec6.png?resize=800x600&vertical=center',
    price: '₹3,499',
    turnaround: '3-4 Days',
    rating: 4.9,
    reviews: 146,
    desc: 'Original character turnaround sheets for animation, comics, gaming, and promotional storytelling.',
    deliverables: ['Front, Side & Back Turnaround', 'Layered Vector File']
  },
  {
    id: 'tattoo-design',
    name: 'Tattoo Design',
    categorySlug: 'Art-Illustration',
    categoryName: 'Art & Illustration',
    image: 'https://cdn.dribbble.com/userupload/45324630/file/d3979b62cfcf4cf3e4bae37f8e67e578.png?resize=800x600&vertical=center',
    price: '₹1,999',
    turnaround: '2-3 Days',
    rating: 4.9,
    reviews: 139,
    desc: 'Custom linework, geometric, realism, or traditional tattoo artwork designed specifically for your skin placement.',
    deliverables: ['Clean Stencil Linework File', 'Shaded Reference Artwork']
  }
];
