// app/lib/templatesData.js

export const categoryTemplateMap = {
  'visiting-cards': {
    name: 'Visiting Cards',
    description: 'Check out a variety of designs for business cards. Find a look that fits your business – and your style.',
    basePrice: '₹200.00',
    unitPriceText: '₹2.00 each / 100 units',
    rating: '4.7 (1,519)',
    filterOptions: {
      color: ['Black', 'Blue', 'Gold', 'Red', 'Green', 'White', 'Multi'],
      orientation: ['Horizontal', 'Vertical', 'Square'],
      corners: ['Standard', 'Rounded'],
      stock: ['Standard Matte', 'Premium Glossy', 'Ultra Thick 350 GSM', 'Textured Cotton'],
      finish: ['Matte', 'Glossy', 'Gold Foil Accent', 'Spot UV Effect'],
      industry: ['Corporate & Executive', 'Creative & Design', 'Medical & Healthcare', 'Food & Restaurant', 'Salon & Spa', 'Real Estate', 'Education & Coaching', 'Retail & E-commerce'],
      style: ['Minimalist', 'Bold & Modern', 'Elegant & Luxury', 'Geometric', 'Vintage & Classic'],
      logoArea: ['With Photo Area', 'With Logo Space', 'Text Only Layout'],
      useCase: ['Networking & Business', 'Appointment & Loyalty', 'Corporate ID', 'Event Pass']
    },
    templates: [
      {
        id: 'vc-1',
        title: 'Minimalist Blue Edge Executive Card',
        companyName: 'Apex Financial Solutions',
        personName: 'Alexander Wright',
        jobTitle: 'Senior Investment Advisor',
        price: '₹200.00',
        unitPrice: '₹2.00 each / 100 units',
        rating: 4.9,
        reviews: 312,
        image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
        colors: ['#2563EB', '#1E293B', '#10B981', '#F59E0B'],
        orientation: 'Horizontal',
        corners: 'Standard',
        stock: 'Standard Matte',
        finish: 'Matte',
        industry: 'Corporate & Executive',
        style: 'Minimalist',
        logoArea: 'With Logo Space',
        useCase: 'Networking & Business',
        badge: 'Bestseller'
      },
      {
        id: 'vc-2',
        title: 'Luxury Gold Foil Black Identity Card',
        companyName: 'Vanguard Luxury Real Estate',
        personName: 'Sophia Montgomery',
        jobTitle: 'Managing Partner',
        price: '₹280.00',
        unitPrice: '₹2.80 each / 100 units',
        rating: 4.8,
        reviews: 245,
        image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        colors: ['#D97706', '#0F172A', '#DC2626', '#475569'],
        orientation: 'Horizontal',
        corners: 'Rounded',
        stock: 'Ultra Thick 350 GSM',
        finish: 'Gold Foil Accent',
        industry: 'Real Estate',
        style: 'Elegant & Luxury',
        logoArea: 'With Logo Space',
        useCase: 'Networking & Business',
        badge: 'Popular'
      },
      {
        id: 'vc-3',
        title: 'Geometric Modern Creative Studio Card',
        companyName: 'Studio Chroma Design',
        personName: 'Liam Reynolds',
        jobTitle: 'Creative Director',
        price: '₹220.00',
        unitPrice: '₹2.20 each / 100 units',
        rating: 4.9,
        reviews: 189,
        image: 'https://images.unsplash.com/photo-1542744094-3a3e22035383?auto=format&fit=crop&w=600&q=80',
        colors: ['#06B6D4', '#8B5CF6', '#EC4899', '#10B981'],
        orientation: 'Horizontal',
        corners: 'Standard',
        stock: 'Premium Glossy',
        finish: 'Glossy',
        industry: 'Creative & Design',
        style: 'Bold & Modern',
        logoArea: 'With Logo Space',
        useCase: 'Networking & Business',
        badge: 'Trending'
      },
      {
        id: 'vc-4',
        title: 'Medical Caduceus Professional Card',
        companyName: 'Metro Healthcare Center',
        personName: 'Dr. Evelyn Reed',
        jobTitle: 'Chief Cardiology Specialist',
        price: '₹200.00',
        unitPrice: '₹2.00 each / 100 units',
        rating: 4.7,
        reviews: 156,
        image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=600&q=80',
        colors: ['#0D9488', '#1E3A8A', '#047857', '#64748B'],
        orientation: 'Horizontal',
        corners: 'Standard',
        stock: 'Standard Matte',
        finish: 'Matte',
        industry: 'Medical & Healthcare',
        style: 'Minimalist',
        logoArea: 'With Logo Space',
        useCase: 'Appointment & Loyalty'
      },
      {
        id: 'vc-5',
        title: 'Soft Pastel Floral Aesthetic Salon Card',
        companyName: 'Aura Botanical Spa & Beauty',
        personName: 'Chloe Bennett',
        jobTitle: 'Founder & Lead Stylist',
        price: '₹240.00',
        unitPrice: '₹2.40 each / 100 units',
        rating: 4.8,
        reviews: 210,
        image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
        colors: ['#F43F5E', '#EC4899', '#D97706', '#8B5CF6'],
        orientation: 'Horizontal',
        corners: 'Rounded',
        stock: 'Textured Cotton',
        finish: 'Matte',
        industry: 'Salon & Spa',
        style: 'Elegant & Luxury',
        logoArea: 'With Photo Area',
        useCase: 'Appointment & Loyalty',
        badge: 'Top Rated'
      },
      {
        id: 'vc-6',
        title: 'Vertical Minimalist Architect Card',
        companyName: 'Modus Architecture Group',
        personName: 'Julian Thorne',
        jobTitle: 'Principal Architect',
        price: '₹220.00',
        unitPrice: '₹2.20 each / 100 units',
        rating: 4.9,
        reviews: 142,
        image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80',
        colors: ['#334155', '#D97706', '#2563EB', '#059669'],
        orientation: 'Vertical',
        corners: 'Standard',
        stock: 'Ultra Thick 350 GSM',
        finish: 'Spot UV Effect',
        industry: 'Real Estate',
        style: 'Minimalist',
        logoArea: 'Text Only Layout',
        useCase: 'Networking & Business'
      },
      {
        id: 'vc-7',
        title: 'Artisanal Cafe & Bistro Loyalty Card',
        companyName: 'The Roast & Grain Coffee Bar',
        personName: 'Marco Bellini',
        jobTitle: 'Head Barista',
        price: '₹190.00',
        unitPrice: '₹1.90 each / 100 units',
        rating: 4.6,
        reviews: 98,
        image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80',
        colors: ['#78350F', '#B45309', '#1E293B', '#15803D'],
        orientation: 'Horizontal',
        corners: 'Rounded',
        stock: 'Textured Cotton',
        finish: 'Matte',
        industry: 'Food & Restaurant',
        style: 'Vintage & Classic',
        logoArea: 'With Logo Space',
        useCase: 'Appointment & Loyalty'
      },
      {
        id: 'vc-8',
        title: 'Tech Startup QR Code Connect Card',
        companyName: 'NexGen Cloud AI',
        personName: 'David Chen',
        jobTitle: 'Lead Product Manager',
        price: '₹250.00',
        unitPrice: '₹2.50 each / 100 units',
        rating: 4.9,
        reviews: 270,
        image: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80',
        colors: ['#3B82F6', '#6366F1', '#10B981', '#F59E0B'],
        orientation: 'Square',
        corners: 'Rounded',
        stock: 'Premium Glossy',
        finish: 'Spot UV Effect',
        industry: 'Corporate & Executive',
        style: 'Bold & Modern',
        logoArea: 'With Photo Area',
        useCase: 'Networking & Business',
        badge: 'Trending'
      }
    ]
  },

  'custom-tshirts': {
    name: 'Custom T-Shirts & Apparel',
    description: 'Explore trendy and professional graphic artwork templates for custom printed t-shirts, polo jerseys, and merchandise.',
    basePrice: '₹349.00',
    unitPriceText: '₹349.00 / shirt (Discounts on bulk)',
    rating: '4.8 (984)',
    filterOptions: {
      color: ['Black', 'White', 'Navy Blue', 'Red', 'Olive Green', 'Mustard', 'Heather Grey'],
      orientation: ['Front Print Only', 'Back Print Only', 'Front & Back Combo', 'Pocket Logo'],
      corners: ['Crew Neck Regular', 'Oversized Fit', 'Polo Collar Fit'],
      stock: ['180 GSM 100% Cotton', '220 GSM Heavy French Terry', 'Bio-Washed Combed Cotton'],
      finish: ['Screen Print', 'DTF High-Definition', 'Puff 3D Emboss Print', 'Premium Embroidery'],
      industry: ['Casual & Streetwear', 'Corporate Team Uniform', 'College & University Fest', 'Gym & Fitness', 'Music & Events', 'Sports & E-sports'],
      style: ['Typography & Quotes', 'Retro & Vintage', 'Minimalist Logo', 'Abstract & Aesthetic', 'Anime & Illustration'],
      logoArea: ['Full Chest Artwork', 'Left Pocket Crest', 'Large Back Graphic'],
      useCase: ['Corporate Gifting', 'Merchandise Sales', 'Event Staff Uniform', 'Personal Style']
    },
    templates: [
      {
        id: 'ts-1',
        title: 'Urban Streetwear Typography Oversized Tee',
        companyName: 'Never Settle Apparel',
        personName: 'Est. 2026',
        jobTitle: 'Limited Edition Series',
        price: '₹449.00',
        unitPrice: '₹449 each (Oversized 220 GSM)',
        rating: 4.9,
        reviews: 420,
        image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
        colors: ['#111827', '#F9FAFB', '#4B5563', '#B45309'],
        orientation: 'Front & Back Combo',
        corners: 'Oversized Fit',
        stock: '220 GSM Heavy French Terry',
        finish: 'DTF High-Definition',
        industry: 'Casual & Streetwear',
        style: 'Typography & Quotes',
        logoArea: 'Large Back Graphic',
        useCase: 'Personal Style',
        badge: 'Bestseller'
      },
      {
        id: 'ts-2',
        title: 'Corporate Tech Team Hackathon Polo',
        companyName: 'CloudScale Developers Group',
        personName: 'Annual Hackathon 2026',
        jobTitle: 'Innovate. Build. Deploy.',
        price: '₹399.00',
        unitPrice: '₹399 each (Min. 10 units)',
        rating: 4.8,
        reviews: 180,
        image: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=600&q=80',
        colors: ['#1E3A8A', '#111827', '#047857', '#DC2626'],
        orientation: 'Pocket Logo',
        corners: 'Polo Collar Fit',
        stock: '180 GSM 100% Cotton',
        finish: 'Premium Embroidery',
        industry: 'Corporate Team Uniform',
        style: 'Minimalist Logo',
        logoArea: 'Left Pocket Crest',
        useCase: 'Corporate Gifting',
        badge: 'Popular'
      },
      {
        id: 'ts-3',
        title: 'Retro Sunset Wave Surf Club Graphic Tee',
        companyName: 'Pacific Coast Surf Co.',
        personName: 'Endless Summer',
        jobTitle: 'Malibu Beach Club',
        price: '₹349.00',
        unitPrice: '₹349 each (Bio-Washed Cotton)',
        rating: 4.9,
        reviews: 310,
        image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=600&q=80',
        colors: ['#F59E0B', '#EF4444', '#3B82F6', '#10B981'],
        orientation: 'Front Print Only',
        corners: 'Crew Neck Regular',
        stock: 'Bio-Washed Combed Cotton',
        finish: 'Screen Print',
        industry: 'Casual & Streetwear',
        style: 'Retro & Vintage',
        logoArea: 'Full Chest Artwork',
        useCase: 'Merchandise Sales',
        badge: 'Trending'
      },
      {
        id: 'ts-4',
        title: 'Iron Performance Gym & Crossfit Tank',
        companyName: 'Titanium Fitness Club',
        personName: 'No Limits',
        jobTitle: 'Strength & Conditioning',
        price: '₹379.00',
        unitPrice: '₹379 each (Moisture Wicking)',
        rating: 4.7,
        reviews: 145,
        image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=600&q=80',
        colors: ['#1F2937', '#DC2626', '#2563EB', '#059669'],
        orientation: 'Front Print Only',
        corners: 'Crew Neck Regular',
        stock: '180 GSM 100% Cotton',
        finish: 'Screen Print',
        industry: 'Gym & Fitness',
        style: 'Typography & Quotes',
        logoArea: 'Full Chest Artwork',
        useCase: 'Event Staff Uniform'
      },
      {
        id: 'ts-5',
        title: 'College Fest & Marathon Event Staff Tee',
        companyName: 'Horizon Youth Festival 2026',
        personName: 'Volunteer Crew',
        jobTitle: 'Official Staff Member',
        price: '₹320.00',
        unitPrice: '₹320 each / 50+ units',
        rating: 4.8,
        reviews: 215,
        image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=600&q=80',
        colors: ['#7C3AED', '#EC4899', '#3B82F6', '#F59E0B'],
        orientation: 'Front & Back Combo',
        corners: 'Crew Neck Regular',
        stock: '180 GSM 100% Cotton',
        finish: 'DTF High-Definition',
        industry: 'College & University Fest',
        style: 'Abstract & Aesthetic',
        logoArea: 'Full Chest Artwork',
        useCase: 'Event Staff Uniform'
      }
    ]
  },

  'banner-poster': {
    name: 'Banner & Poster Printing',
    description: 'High-visibility display templates for retail store promotions, corporate events, exhibition roll-up stands, and real estate hoardings.',
    basePrice: '₹499.00',
    unitPriceText: '₹499.00 / Banner (Standard 4x2 ft)',
    rating: '4.8 (812)',
    filterOptions: {
      color: ['Red & Yellow Promo', 'Blue & White Corporate', 'Black & Gold Luxury', 'Green Eco Theme', 'Vibrant Multi'],
      orientation: ['Horizontal Outdoor Flex', 'Vertical Roll-up Stand', 'Square Backdrop Panel'],
      corners: ['Metal Eyelets & Grommets', 'Pole Pockets', 'Wooden Frame Mount', 'Self-Adhesive Back'],
      stock: ['Heavy-Duty 340 GSM Flex', 'Star Backlit Vinyl Flex', 'Exhibition Satin Fabric', 'Photo-Grade Poster Paper'],
      finish: ['UV Weatherproof Gloss', 'Anti-Glare Matte Finish', 'High-Res Solvent Print'],
      industry: ['Retail Sale & Offer', 'Corporate Exhibition & Conference', 'Real Estate & Property', 'Grand Opening Event', 'Food & Restaurant Menu', 'Coaching & Education Admission'],
      style: ['High Impact Sale', 'Professional & Clean', 'Modern Minimalist', 'Photo & Product Showcase'],
      logoArea: ['Header Logo Space', 'Full Center Banner', 'Multi-Partner Sponsor Footer'],
      useCase: ['Outdoor Store Hoarding', 'Indoor Exhibition Booth', 'Event Photo Backdrop', 'Street Promotion']
    },
    templates: [
      {
        id: 'bp-1',
        title: 'Grand Opening Big Sale Retail Banner',
        companyName: 'SuperStore Hypermarket',
        personName: '50% Flat Discount',
        jobTitle: 'Offer Valid This Weekend Only',
        price: '₹499.00',
        unitPrice: '₹499 (4x2 ft Heavy Vinyl)',
        rating: 4.9,
        reviews: 290,
        image: 'https://images.unsplash.com/photo-1542744094-3a3e22035383?auto=format&fit=crop&w=600&q=80',
        colors: ['#EF4444', '#F59E0B', '#1E293B', '#10B981'],
        orientation: 'Horizontal Outdoor Flex',
        corners: 'Metal Eyelets & Grommets',
        stock: 'Heavy-Duty 340 GSM Flex',
        finish: 'UV Weatherproof Gloss',
        industry: 'Retail Sale & Offer',
        style: 'High Impact Sale',
        logoArea: 'Header Logo Space',
        useCase: 'Outdoor Store Hoarding',
        badge: 'Bestseller'
      },
      {
        id: 'bp-2',
        title: 'Corporate Exhibition Roll-Up Standee',
        companyName: 'Global AI Summit 2026',
        personName: 'The Future of Automation',
        jobTitle: 'Visit Booth #42 | Speakers & Live Demo',
        price: '₹1,299.00',
        unitPrice: '₹1,299 with Aluminum Stand (6x3 ft)',
        rating: 4.9,
        reviews: 240,
        image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=600&q=80',
        colors: ['#2563EB', '#1E293B', '#06B6D4', '#64748B'],
        orientation: 'Vertical Roll-up Stand',
        corners: 'Pole Pockets',
        stock: 'Star Backlit Vinyl Flex',
        finish: 'Anti-Glare Matte Finish',
        industry: 'Corporate Exhibition & Conference',
        style: 'Professional & Clean',
        logoArea: 'Header Logo Space',
        useCase: 'Indoor Exhibition Booth',
        badge: 'Popular'
      },
      {
        id: 'bp-3',
        title: 'Luxury Residential Real Estate Hoarding',
        companyName: 'Skyline Heritage Residences',
        personName: '3 & 4 BHK Luxury Apartments',
        jobTitle: 'Booking Open | Prime Location | Gym & Pool',
        price: '₹1,899.00',
        unitPrice: '₹1,899 (8x4 ft Outdoor Hoarding)',
        rating: 4.8,
        reviews: 175,
        image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=600&q=80',
        colors: ['#B45309', '#0F172A', '#047857', '#334155'],
        orientation: 'Horizontal Outdoor Flex',
        corners: 'Metal Eyelets & Grommets',
        stock: 'Heavy-Duty 340 GSM Flex',
        finish: 'UV Weatherproof Gloss',
        industry: 'Real Estate & Property',
        style: 'Professional & Clean',
        logoArea: 'Header Logo Space',
        useCase: 'Outdoor Store Hoarding',
        badge: 'Trending'
      },
      {
        id: 'bp-4',
        title: 'Restaurant Delicious Special Menu Poster',
        companyName: 'Flavors of Italy Kitchen',
        personName: 'Authentic Wood-Fired Pizza',
        jobTitle: 'Fresh Pasta | Gelato | Dine-in & Delivery',
        price: '₹349.00',
        unitPrice: '₹349 (A1 Size Photo Grade Poster)',
        rating: 4.7,
        reviews: 130,
        image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
        colors: ['#991B1B', '#D97706', '#15803D', '#1E293B'],
        orientation: 'Vertical Roll-up Stand',
        corners: 'Self-Adhesive Back',
        stock: 'Photo-Grade Poster Paper',
        finish: 'High-Res Solvent Print',
        industry: 'Food & Restaurant Menu',
        style: 'Photo & Product Showcase',
        logoArea: 'Full Center Banner',
        useCase: 'Indoor Exhibition Booth'
      }
    ]
  },

  'flex-board': {
    name: 'Flex Board & Signage',
    description: 'Durable weather-resistant glow sign boards, shopfront frontlit boards, and 3D acrylic LED templates.',
    basePrice: '₹650.00',
    unitPriceText: '₹650.00 / sq. mt (With frame options)',
    rating: '4.8 (645)',
    filterOptions: {
      color: ['Bright LED White', 'Golden Glow', 'Royal Blue', 'Deep Red', 'Emerald Green'],
      orientation: ['Horizontal Shopfront', 'Vertical Pillar Sign', 'Projecting Blade Board'],
      corners: ['Heavy Iron Box Frame', '3D Acrylic Letters', 'Aluminum Border Frame', 'Backlit Glow Box'],
      stock: ['Frontlit Weatherproof Vinyl', 'Backlit Star Flex', 'Sunboard Vinyl Panel', '3D Raised Acrylic Lettering'],
      finish: ['UV Protected Gloss', 'LED Backlit Glow', 'Reflective Night-Glow'],
      industry: ['Medical Pharmacy Store', 'Supermarket & Grocery', 'Restaurant & Cafe Front', 'Jewelry & Fashion Boutique', 'Automotive & Workshop', 'Hardware & Electronics'],
      style: ['Modern LED Glow', 'Bold & High Visibility', 'Classic Framed', 'Minimalist Luxury'],
      logoArea: ['Prominent Center Emblem', 'Left Aligned Icon', 'Full Width Typography'],
      useCase: ['Storefront Main Board', 'Highway Guidance Sign', 'Indoor Reception Crest', 'Roof Top Hoarding']
    },
    templates: [
      {
        id: 'fb-1',
        title: 'Modern LED Backlit Pharmacy Glow Sign',
        companyName: 'LifePlus 24/7 Pharmacy & Medical Store',
        personName: 'Prescription Drugs & Healthcare Supplies',
        jobTitle: 'Home Delivery Available | 10% Off All Medicines',
        price: '₹2,499.00',
        unitPrice: '₹2,499 (Complete Backlit Glow Board)',
        rating: 4.9,
        reviews: 210,
        image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80',
        colors: ['#047857', '#1E3A8A', '#DC2626', '#F59E0B'],
        orientation: 'Horizontal Shopfront',
        corners: 'Backlit Glow Box',
        stock: 'Backlit Star Flex',
        finish: 'LED Backlit Glow',
        industry: 'Medical Pharmacy Store',
        style: 'Modern LED Glow',
        logoArea: 'Prominent Center Emblem',
        useCase: 'Storefront Main Board',
        badge: 'Bestseller'
      },
      {
        id: 'fb-2',
        title: '3D Acrylic Letter Luxury Boutique Board',
        companyName: 'Velvet & Silk Haute Couture',
        personName: 'Bridal Wear & Designer Sarees',
        jobTitle: 'Exclusive Custom Fittings | Luxury Studio',
        price: '₹4,500.00',
        unitPrice: '₹4,500 (3D Raised Acrylic Letters on ACP)',
        rating: 4.9,
        reviews: 168,
        image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=600&q=80',
        colors: ['#D97706', '#0F172A', '#BE185D', '#475569'],
        orientation: 'Horizontal Shopfront',
        corners: '3D Acrylic Letters',
        stock: '3D Raised Acrylic Lettering',
        finish: 'UV Protected Gloss',
        industry: 'Jewelry & Fashion Boutique',
        style: 'Minimalist Luxury',
        logoArea: 'Prominent Center Emblem',
        useCase: 'Storefront Main Board',
        badge: 'Premium'
      },
      {
        id: 'fb-3',
        title: 'Heavy Iron Frame Grocery & Supermarket Board',
        companyName: 'FreshMart Daily Needs & Provisions',
        personName: 'Groceries, Fruits, Dairy & Beverages',
        jobTitle: 'Free Home Delivery Within 5 KMs',
        price: '₹1,499.00',
        unitPrice: '₹1,499 (6x3 ft Iron Framed Frontlit)',
        rating: 4.7,
        reviews: 132,
        image: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=600&q=80',
        colors: ['#DC2626', '#16A34A', '#2563EB', '#EAB308'],
        orientation: 'Horizontal Shopfront',
        corners: 'Heavy Iron Box Frame',
        stock: 'Frontlit Weatherproof Vinyl',
        finish: 'UV Protected Gloss',
        industry: 'Supermarket & Grocery',
        style: 'Bold & High Visibility',
        logoArea: 'Prominent Center Emblem',
        useCase: 'Storefront Main Board'
      }
    ]
  },

  'packaging-labeling': {
    name: 'Packaging, Boxes & Stickers',
    description: 'Custom corrugated boxes, product labels, waterproof stickers, Kraft paper bags, and luxury rigid gift boxes.',
    basePrice: '₹150.00',
    unitPriceText: '₹1.50 each / 100 stickers or labels',
    rating: '4.9 (734)',
    filterOptions: {
      color: ['Kraft Brown Natural', 'Minimalist White & Black', 'Gold Foil & Navy', 'Pastel Pink & Cream', 'Bright Eco Green'],
      orientation: ['Bottle / Jar Label', 'Box Packaging Template', 'Shopping Bag Layout', 'Die-Cut Sticker'],
      corners: ['Square Cut', 'Round Corner Sticker', 'Die-Cut Custom Shape', 'Pouch Layout'],
      stock: ['Waterproof Vinyl Sticker', 'Corrugated E-Flute Box', 'Kraft Paper Shopping Bag', 'Art Paper Label', 'Luxury Rigid Cardboard'],
      finish: ['Matte Lamination', 'High Gloss Finish', 'Gold / Silver Hot Stamping', 'Embossed Texture'],
      industry: ['Organic & Gourmet Food', 'Cosmetics & Skincare', 'E-Commerce & D2C Shipping', 'Artisanal Bakery & Cafe', 'Perfume & Luxury Gifts', 'Pharmaceuticals'],
      style: ['Minimalist & Organic', 'Luxury Foil Accent', 'Bold D2C Branding', 'Handmade & Craft'],
      logoArea: ['Center Brand Emblem', 'Top Flap Logo', 'Wrap-Around Banner'],
      useCase: ['Product Jar & Bottle', 'Shipping Box & Mailer', 'Retail Bag Gifting', 'Brand Seal & Tag']
    },
    templates: [
      {
        id: 'pl-1',
        title: 'Botanical Skincare Waterproof Glass Bottle Label',
        companyName: 'PureBotanicals Organics',
        personName: 'Vitamin C + Hyaluronic Acid Serum',
        jobTitle: '100% Vegan | Cruelty Free | Net Wt. 50ml',
        price: '₹150.00',
        unitPrice: '₹1.50 each / 100 waterproof labels',
        rating: 4.9,
        reviews: 280,
        image: 'https://images.unsplash.com/photo-1608248597359-0e6d526a67e8?auto=format&fit=crop&w=600&q=80',
        colors: ['#065F46', '#F0FDF4', '#D97706', '#1E293B'],
        orientation: 'Bottle / Jar Label',
        corners: 'Round Corner Sticker',
        stock: 'Waterproof Vinyl Sticker',
        finish: 'Matte Lamination',
        industry: 'Cosmetics & Skincare',
        style: 'Minimalist & Organic',
        logoArea: 'Center Brand Emblem',
        useCase: 'Product Jar & Bottle',
        badge: 'Bestseller'
      },
      {
        id: 'pl-2',
        title: 'Custom Printed Corrugated E-Commerce Mailer Box',
        companyName: 'Vibe & Co. Lifestyle',
        personName: 'Crafted For You With Care',
        jobTitle: 'Unbox Happiness | Share Your Review #VibeStyle',
        price: '₹2,500.00',
        unitPrice: '₹25 each / 100 custom boxes',
        rating: 4.8,
        reviews: 195,
        image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=600&q=80',
        colors: ['#D97706', '#1E293B', '#3B82F6', '#10B981'],
        orientation: 'Box Packaging Template',
        corners: 'Square Cut',
        stock: 'Corrugated E-Flute Box',
        finish: 'Matte Lamination',
        industry: 'E-Commerce & D2C Shipping',
        style: 'Bold D2C Branding',
        logoArea: 'Top Flap Logo',
        useCase: 'Shipping Box & Mailer',
        badge: 'Popular'
      },
      {
        id: 'pl-3',
        title: 'Artisanal Bakery & Coffee Kraft Shopping Bag',
        companyName: 'La Boulangerie Artisan Bakery',
        personName: 'Freshly Baked Croissants & Sourdough',
        jobTitle: 'Organic Ingredients | Handcrafted Daily',
        price: '₹1,200.00',
        unitPrice: '₹12 each / 100 Kraft Paper Bags',
        rating: 4.9,
        reviews: 154,
        image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=600&q=80',
        colors: ['#78350F', '#FDE68A', '#1E293B', '#15803D'],
        orientation: 'Shopping Bag Layout',
        corners: 'Square Cut',
        stock: 'Kraft Paper Shopping Bag',
        finish: 'Matte Lamination',
        industry: 'Artisanal Bakery & Cafe',
        style: 'Handmade & Craft',
        logoArea: 'Center Brand Emblem',
        useCase: 'Retail Bag Gifting',
        badge: 'Trending'
      }
    ]
  },

  'mugs-drinkware': {
    name: 'Custom Mugs & Drinkware',
    description: 'Personalized ceramic coffee mugs, insulated travel tumblers, magic photo reveal mugs, and corporate branded flasks.',
    basePrice: '₹199.00',
    unitPriceText: '₹199.00 / Ceramic Mug (11 oz)',
    rating: '4.8 (521)',
    filterOptions: {
      color: ['Glossy White', 'Matte Black', 'Inside Color Rim', 'Magic Black Reveal', 'Metallic Silver'],
      orientation: ['Full Wrap Around Print', 'Front & Back Logo', 'Single Side Photo'],
      corners: ['11 oz Standard Mug', '15 oz Large Mug', 'Insulated Steel Flask', 'Travel Sipper Mug'],
      stock: ['High-Grade White Ceramic', 'Color Changing Magic Ceramic', 'Food-Grade Stainless Steel'],
      finish: ['Sublimation High-Gloss', 'Laser Engraved Metallic', 'Matte Ceramic Finish'],
      industry: ['Corporate Employee Gift', 'Anniversary & Birthday Gift', 'Cafe & Restaurant Serveware', 'Souvenir & Merchandise'],
      style: ['Motivational Quote', 'Company Logo Branding', 'Photo Collage', 'Minimalist Typography'],
      logoArea: ['Full Wrap Artwork', 'Center Front Emblem', 'Double Sided Crest'],
      useCase: ['Office Desk Mug', 'Gift Box Combo', 'Event Giveaways', 'Daily Coffee Mug']
    },
    templates: [
      {
        id: 'mg-1',
        title: 'Corporate Welcome Kit Branded Ceramic Mug',
        companyName: 'InnovateX Global Technologies',
        personName: 'Dream. Build. Achieve.',
        jobTitle: 'Welcome to the Team | #WeAreInnovateX',
        price: '₹199.00',
        unitPrice: '₹199 each (11 oz High-Grade Ceramic)',
        rating: 4.9,
        reviews: 210,
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
        colors: ['#2563EB', '#1E293B', '#10B981', '#DC2626'],
        orientation: 'Front & Back Logo',
        corners: '11 oz Standard Mug',
        stock: 'High-Grade White Ceramic',
        finish: 'Sublimation High-Gloss',
        industry: 'Corporate Employee Gift',
        style: 'Company Logo Branding',
        logoArea: 'Double Sided Crest',
        useCase: 'Office Desk Mug',
        badge: 'Bestseller'
      },
      {
        id: 'mg-2',
        title: 'Magic Color Changing Photo Reveal Coffee Mug',
        companyName: 'Memories Forever Keepsakes',
        personName: 'Best Friends Forever',
        jobTitle: 'Pour Hot Coffee to Reveal Your Custom Photo & Message!',
        price: '₹299.00',
        unitPrice: '₹299 each (Magic Heat-Sensitive Ceramic)',
        rating: 4.8,
        reviews: 178,
        image: 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?auto=format&fit=crop&w=600&q=80',
        colors: ['#111827', '#EF4444', '#8B5CF6', '#F59E0B'],
        orientation: 'Full Wrap Around Print',
        corners: '11 oz Standard Mug',
        stock: 'Color Changing Magic Ceramic',
        finish: 'Sublimation High-Gloss',
        industry: 'Anniversary & Birthday Gift',
        style: 'Photo Collage',
        logoArea: 'Full Wrap Artwork',
        useCase: 'Gift Box Combo',
        badge: 'Popular'
      }
    ]
  },

  'hoodies-jackets': {
    name: 'Hoodies & Winterwear',
    description: 'Premium heavy fleece hoodies, zipper jackets, varsity jackets, and sweatshirts with high-density puff print and embroidery.',
    basePrice: '₹799.00',
    unitPriceText: '₹799.00 / Hoodie (320 GSM Brushed Fleece)',
    rating: '4.9 (480)',
    filterOptions: {
      color: ['Jet Black', 'Heather Grey', 'Navy Blue', 'Forest Green', 'Maroon Red', 'Beige Cream'],
      orientation: ['Chest Crest + Back Graphic', 'Sleeve Embroidery Only', 'Front Kangaroo Pocket Logo'],
      corners: ['Pullover Hoodie Regular Fit', 'Oversized Streetwear Hoodie', 'Zip-Up Winter Jacket', 'Varsity College Jacket'],
      stock: ['320 GSM 100% Cotton Fleece', '400 GSM Ultra-Heavy Winter Fleece', 'Polyester Windbreaker Fabric'],
      finish: ['3D Puff Emboss Print', 'Premium Chenille & Embroidery', 'High-Density DTF Print'],
      industry: ['Streetwear Fashion Brand', 'University & College Varsity', 'Corporate Winter Uniform', 'Sports & Athlete Club'],
      style: ['Minimalist Chest Logo', 'Bold Back Artwork', 'Varsity & Letterman Style', 'Typography & Slogans'],
      logoArea: ['Full Back Graphic', 'Left Chest Emblem', 'Both Sleeve & Back'],
      useCase: ['Premium Winter Wear', 'Team & Club Apparel', 'Merchandise Drop', 'Corporate Executive Gift']
    },
    templates: [
      {
        id: 'hj-1',
        title: 'Oversized Streetwear 3D Puff Print Hoodie',
        companyName: 'Aesthetic Studios Collection',
        personName: 'Mind Over Matter',
        jobTitle: 'Heavyweight 360 GSM Brushed Fleece',
        price: '₹999.00',
        unitPrice: '₹999 each (Oversized Fit Fleece)',
        rating: 4.9,
        reviews: 260,
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80',
        colors: ['#111827', '#D1D5DB', '#4B5563', '#B45309'],
        orientation: 'Chest Crest + Back Graphic',
        corners: 'Oversized Streetwear Hoodie',
        stock: '400 GSM Ultra-Heavy Winter Fleece',
        finish: '3D Puff Emboss Print',
        industry: 'Streetwear Fashion Brand',
        style: 'Bold Back Artwork',
        logoArea: 'Full Back Graphic',
        useCase: 'Merchandise Drop',
        badge: 'Bestseller'
      },
      {
        id: 'hj-2',
        title: 'College Varsity Letterman Embroidered Jacket',
        companyName: 'Oxford Athletics & Rowing Club',
        personName: 'Class of 2026',
        jobTitle: 'Official University Varsity Jacket | Premium Chenille Patch',
        price: '₹1,499.00',
        unitPrice: '₹1,499 each (Varsity Fleece + Ribbed Cuffs)',
        rating: 4.9,
        reviews: 145,
        image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
        colors: ['#1E3A8A', '#991B1B', '#15803D', '#111827'],
        orientation: 'Chest Crest + Back Graphic',
        corners: 'Varsity College Jacket',
        stock: '320 GSM 100% Cotton Fleece',
        finish: 'Premium Chenille & Embroidery',
        industry: 'University & College Varsity',
        style: 'Varsity & Letterman Style',
        logoArea: 'Left Chest Emblem',
        useCase: 'Team & Club Apparel',
        badge: 'Premium'
      }
    ]
  },

  'logo-identity-design': {
    name: 'Logo & Brand Identity Design',
    description: 'Custom logo concepts, full brand guideline books, stationery kits, and corporate visual identity packages.',
    basePrice: '₹1,499.00',
    unitPriceText: '₹1,499.00 / Complete Logo Suite',
    rating: '4.9 (1,120)',
    filterOptions: {
      color: ['Modern Blue & Cyan', 'Luxury Gold & Black', 'Vibrant Startup Multi', 'Minimalist Monochrome', 'Earthy & Organic Green'],
      orientation: ['Horizontal Combination Mark', 'Square Monogram & Icon', 'Stacked Emblem Logo'],
      corners: ['Vector AI / EPS / SVG Suite', 'Complete Brand Stylebook', 'Stationery Kit Included', 'Social Media Branding Kit'],
      stock: ['Vector Source Files (AI/EPS)', 'Print & Web Ready (PNG/PDF)', '3D Mockup Presentation'],
      finish: ['Flat Minimalist', 'Gradient Modern', 'Luxury Emblem & Foil', 'Geometric Monogram'],
      industry: ['Tech Startup & SaaS', 'Real Estate & Construction', 'Luxury Fashion & Jewelry', 'Restaurant & Cafe Hospitality', 'Consulting & Financial Services', 'Health & Wellness'],
      style: ['Minimalist & Geometric', 'Abstract Symbol', 'Modern Wordmark', 'Vintage & Crest Emblem', 'Mascot & Character'],
      logoArea: ['Icon + Typography Combo', 'Monogram Badge', 'Typography Wordmark Only'],
      useCase: ['New Business Launch', 'Complete Rebranding', 'Corporate Trademarking', 'App & Web Icon']
    },
    templates: [
      {
        id: 'li-1',
        title: 'Minimalist Tech SaaS & AI Startup Logo Suite',
        companyName: 'Quantum AI Systems',
        personName: 'Next-Generation Neural Computing',
        jobTitle: 'Complete Logo Pack: AI, EPS, SVG, High-Res PNG + Dark Mode Variations',
        price: '₹1,499.00',
        unitPrice: '₹1,499 (3 Custom Concepts + Vector Suite)',
        rating: 4.9,
        reviews: 410,
        image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=600&q=80',
        colors: ['#3B82F6', '#6366F1', '#1E293B', '#10B981'],
        orientation: 'Horizontal Combination Mark',
        corners: 'Vector AI / EPS / SVG Suite',
        stock: 'Vector Source Files (AI/EPS)',
        finish: 'Gradient Modern',
        industry: 'Tech Startup & SaaS',
        style: 'Minimalist & Geometric',
        logoArea: 'Icon + Typography Combo',
        useCase: 'New Business Launch',
        badge: 'Bestseller'
      },
      {
        id: 'li-2',
        title: 'Luxury Gold Monogram & Real Estate Crest Logo',
        companyName: 'Crown & Pillar Property Group',
        personName: 'Excellence in Architectural Heritage',
        jobTitle: 'Includes Gold Foil Mockups, Letterhead & Business Card Templates',
        price: '₹2,499.00',
        unitPrice: '₹2,499 (VIP Brand Suite + Style Guidelines)',
        rating: 4.9,
        reviews: 295,
        image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
        colors: ['#D97706', '#0F172A', '#1E293B', '#DC2626'],
        orientation: 'Square Monogram & Icon',
        corners: 'Complete Brand Stylebook',
        stock: 'Vector Source Files (AI/EPS)',
        finish: 'Luxury Emblem & Foil',
        industry: 'Real Estate & Construction',
        style: 'Vintage & Crest Emblem',
        logoArea: 'Monogram Badge',
        useCase: 'Complete Rebranding',
        badge: 'Premium'
      }
    ]
  },

  'graphic-design': {
    name: 'Graphic Design & Vector Artwork',
    description: 'Professional vector tracing, custom infographic layouts, social media ad creatives, 3D renders, and pitch deck presentations.',
    basePrice: '₹499.00',
    unitPriceText: '₹499.00 / Custom Graphic Concept',
    rating: '4.8 (640)',
    filterOptions: {
      color: ['Bold & High Contrast', 'Sleek Corporate Navy', 'Creative Neon Colors', 'Pastel Minimalist'],
      orientation: ['16:9 Presentation / Deck', '1:1 Square Social Media', '9:16 Vertical Story / Reel', 'Custom Vector Tracing'],
      corners: ['Figma / PSD Editable File', 'AI Vector Tracing File', 'High-Res Print & Web Pack'],
      stock: ['Vector EPS / AI Source', 'Figma Presentation Suite', 'High-Res PSD Layers'],
      finish: ['Clean Modern Vector', '3D Product Rendering', 'Isometric Illustration', 'Photo Manipulation'],
      industry: ['Corporate Pitch & Investor Deck', 'E-Commerce Social Media Ads', 'Medical Infographics', 'Event & Concert Promo'],
      style: ['Flat Vector Art', 'Isometric 3D', 'Data Infographic Layout', 'High-Conversion Ad Creative'],
      logoArea: ['Full Page Artwork', 'Structured Grid Deck', 'Vector Icon Set'],
      useCase: ['Investor Pitch Deck', 'Social Media Campaign', 'Vector Conversion Service', 'Product Launch']
    },
    templates: [
      {
        id: 'gd-1',
        title: 'Investor Pitch Deck & Corporate Presentation Suite',
        companyName: 'FinTech Growth Series A Deck',
        personName: '25 Custom Designed Slides',
        jobTitle: 'Figma, PowerPoint & Keynote Formats | Financial Charts & Infographics',
        price: '₹1,999.00',
        unitPrice: '₹1,999 (Complete 25-Slide Editable Suite)',
        rating: 4.9,
        reviews: 240,
        image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=600&q=80',
        colors: ['#1E3A8A', '#3B82F6', '#10B981', '#111827'],
        orientation: '16:9 Presentation / Deck',
        corners: 'Figma / PSD Editable File',
        stock: 'Figma Presentation Suite',
        finish: 'Clean Modern Vector',
        industry: 'Corporate Pitch & Investor Deck',
        style: 'Data Infographic Layout',
        logoArea: 'Structured Grid Deck',
        useCase: 'Investor Pitch Deck',
        badge: 'Bestseller'
      },
      {
        id: 'gd-2',
        title: 'Social Media Campaign Ad Creatives Bundle',
        companyName: 'Mega Festive Sale Ad Pack',
        personName: '12 Instagram Posts + 12 Stories',
        jobTitle: 'High-Converting Ad Layouts | PSD & Canva Editable Formats',
        price: '₹899.00',
        unitPrice: '₹899 (24 Custom Ad Templates Bundle)',
        rating: 4.8,
        reviews: 188,
        image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=600&q=80',
        colors: ['#EC4899', '#8B5CF6', '#F59E0B', '#3B82F6'],
        orientation: '1:1 Square Social Media',
        corners: 'Figma / PSD Editable File',
        stock: 'High-Res PSD Layers',
        finish: '3D Product Rendering',
        industry: 'E-Commerce Social Media Ads',
        style: 'High-Conversion Ad Creative',
        logoArea: 'Full Page Artwork',
        useCase: 'Social Media Campaign',
        badge: 'Popular'
      }
    ]
  },

  'web-design': {
    name: 'Web Design & UI/UX',
    description: 'Custom high-converting website UI layouts, Figma mobile app prototypes, e-commerce storefronts, and dashboard interfaces.',
    basePrice: '₹2,499.00',
    unitPriceText: '₹2,499.00 / Landing Page UI Suite',
    rating: '4.9 (510)',
    filterOptions: {
      color: ['Sleek Dark Mode UI', 'Clean White & Blue SaaS', 'Vibrant Fintech Theme', 'Minimalist Luxury E-Commerce'],
      orientation: ['Desktop + Mobile Responsive', 'Mobile App Only (iOS/Android)', 'Admin Dashboard Panel'],
      corners: ['Complete Figma Source File', 'Interactive Prototyping Included', 'Design System & Component Library'],
      stock: ['Figma Design Suite', 'Adobe XD / Sketch File', 'HTML/Tailwind Design Tokens'],
      finish: ['Glassmorphism Modern UI', 'Clean Minimalist Grid', 'High-Converting Sales Funnel'],
      industry: ['SaaS & Web Application', 'E-Commerce Storefront', 'Fintech & Banking Mobile App', 'Healthcare & Telemedicine Portal', 'Real Estate Listing Platform'],
      style: ['Modern SaaS UI', 'Luxury E-Commerce Catalog', 'Dashboard & Analytics Panel', 'Interactive App Prototype'],
      logoArea: ['Complete Multi-Section Layout', 'Component Library Included', 'Mobile Screen Flow'],
      useCase: ['Website Redesign & UI', 'New App Launch', 'SaaS Dashboard UI', 'High-Converting Sales Page']
    },
    templates: [
      {
        id: 'wd-1',
        title: 'High-Converting SaaS Landing Page + Dashboard UI Suite',
        companyName: 'CloudPro AI Analytics Platform',
        personName: 'Complete Desktop & Mobile Figma Files',
        jobTitle: 'Includes Hero Section, Feature Grid, Pricing Cards, FAQ & Interactive Prototyping',
        price: '₹2,499.00',
        unitPrice: '₹2,499 (Full Landing Page + Component Library)',
        rating: 4.9,
        reviews: 215,
        image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=600&q=80',
        colors: ['#0F172A', '#3B82F6', '#10B981', '#8B5CF6'],
        orientation: 'Desktop + Mobile Responsive',
        corners: 'Complete Figma Source File',
        stock: 'Figma Design Suite',
        finish: 'Glassmorphism Modern UI',
        industry: 'SaaS & Web Application',
        style: 'Modern SaaS UI',
        logoArea: 'Complete Multi-Section Layout',
        useCase: 'Website Redesign & UI',
        badge: 'Bestseller'
      },
      {
        id: 'wd-2',
        title: 'Luxury Fashion E-Commerce Storefront UI & App Screens',
        companyName: 'LuxeCart Global Storefront',
        personName: 'Product Listing, Detail Page & Cart Checkout Flow',
        jobTitle: 'Sleek Minimalist Typography | Responsive Design for Web & iOS',
        price: '₹3,499.00',
        unitPrice: '₹3,499 (10 Complete E-Commerce Pages + App UI)',
        rating: 4.9,
        reviews: 172,
        image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
        colors: ['#111827', '#F3F4F6', '#D97706', '#991B1B'],
        orientation: 'Desktop + Mobile Responsive',
        corners: 'Design System & Component Library',
        stock: 'Figma Design Suite',
        finish: 'Clean Minimalist Grid',
        industry: 'E-Commerce Storefront',
        style: 'Luxury E-Commerce Catalog',
        logoArea: 'Complete Multi-Section Layout',
        useCase: 'New App Launch',
        badge: 'Premium'
      }
    ]
  },

  'print-design': {
    name: 'Print Design & Marketing Collateral',
    description: 'Custom multi-page product catalogs, tri-fold brochures, promotional flyers, restaurant menus, and corporate annual reports.',
    basePrice: '₹399.00',
    unitPriceText: '₹399.00 / Brochure or Flyer Design',
    rating: '4.8 (690)',
    filterOptions: {
      color: ['Corporate Blue & Grey', 'Vibrant Red & Yellow Promo', 'Minimalist Black & White', 'Warm Hospitality Gold'],
      orientation: ['Bi-Fold Brochure Layout', 'Tri-Fold Marketing Leaflet', 'A4 Flyer & Handout', 'Multi-Page Catalog'],
      corners: ['High-Res Print Ready PDF (CMYK)', 'Source InDesign / Illustrator File', 'Editable Word / PDF Form'],
      stock: ['300 DPI Print-Ready PDF', 'Adobe InDesign Source Suite', 'Illustrator AI / EPS Layers'],
      finish: ['Editorial Clean Typography', 'Photo Showcase Grid', 'Infographic & Table Layout'],
      industry: ['Corporate Business Brochure', 'Restaurant & Bar Menu Design', 'Real Estate Property Booklet', 'Product Catalog & Price List', 'Healthcare Patient Brochure'],
      style: ['Professional & Editorial', 'High-Impact Promotional', 'Elegant & Luxury Booklet', 'Clean Corporate Grid'],
      logoArea: ['Cover Page & Header Crest', 'Full Multi-Page Booklet', 'Tri-Fold Panel Flow'],
      useCase: ['Corporate Sales Brochure', 'Restaurant Dine-In Menu', 'Exhibition Product Catalog', 'Direct Mail Flyer']
    },
    templates: [
      {
        id: 'pd-1',
        title: 'Corporate Tri-Fold Business & Marketing Brochure',
        companyName: 'Apex Strategic Consulting Group',
        personName: 'Our Services, Mission & Case Studies',
        jobTitle: 'Includes Front & Back 6-Panel Layout | CMYK Print-Ready AI & PDF',
        price: '₹499.00',
        unitPrice: '₹499 (Complete Tri-Fold Editable Source)',
        rating: 4.9,
        reviews: 280,
        image: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?auto=format&fit=crop&w=600&q=80',
        colors: ['#1E3A8A', '#0F172A', '#0EA5E9', '#F8FAFC'],
        orientation: 'Tri-Fold Marketing Leaflet',
        corners: 'High-Res Print Ready PDF (CMYK)',
        stock: '300 DPI Print-Ready PDF',
        finish: 'Editorial Clean Typography',
        industry: 'Corporate Business Brochure',
        style: 'Professional & Editorial',
        logoArea: 'Tri-Fold Panel Flow',
        useCase: 'Corporate Sales Brochure',
        badge: 'Bestseller'
      },
      {
        id: 'pd-2',
        title: 'Multi-Page Product Catalog & Price Guide Booklet',
        companyName: 'Industrial Hardware & Supplies 2026',
        personName: '16-Page Master Product Directory',
        jobTitle: 'Clean Grid Layout for Products, Specs & Prices | Adobe InDesign Suite',
        price: '₹1,899.00',
        unitPrice: '₹1,899 (16-Page Complete Catalog Template)',
        rating: 4.8,
        reviews: 140,
        image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80',
        colors: ['#B45309', '#1E293B', '#DC2626', '#334155'],
        orientation: 'Multi-Page Catalog',
        corners: 'Source InDesign / Illustrator File',
        stock: 'Adobe InDesign Source Suite',
        finish: 'Infographic & Table Layout',
        industry: 'Product Catalog & Price List',
        style: 'Clean Corporate Grid',
        logoArea: 'Full Multi-Page Booklet',
        useCase: 'Exhibition Product Catalog',
        badge: 'Popular'
      }
    ]
  },

  'Art-Illustration': {
    name: 'Art & Custom Illustration',
    description: 'Bespoke vector illustrations, brand mascot characters, book covers, custom digital concept art, and creative artwork.',
    basePrice: '₹799.00',
    unitPriceText: '₹799.00 / Custom Vector Illustration',
    rating: '4.9 (430)',
    filterOptions: {
      color: ['Vibrant & Colorful Art', 'Minimalist Line Art', 'Vintage Comic Book Palette', 'Digital Watercolor Pastel'],
      orientation: ['Square Vector Artwork', 'Vertical Book Cover', 'Horizontal Banner & Storyboard'],
      corners: ['Vector AI / EPS / SVG File', 'High-Res Digital Canvas PNG/PSD', 'Complete Character Turnaround Sheet'],
      stock: ['Vector EPS / AI Source', 'High-Res PSD Layered Canvas', 'Procreate / Digital Painting Suite'],
      finish: ['Clean Vector Line & Fill', 'Detailed Digital Painting', 'Flat Isometric Style', 'Comic & Storyboard Art'],
      industry: ['Brand Mascot & Character', 'Book & Editorial Cover', 'Gaming & Concept Art', 'App & Web Illustration Pack'],
      style: ['Flat Vector Character', '3D Cute Mascot', 'Detailed Fantasy Concept', 'Minimalist Line Art'],
      logoArea: ['Center Character Emblem', 'Full Canvas Story Scene', 'Icon Set Suite'],
      useCase: ['Brand Character Identity', 'Book & Magazine Cover', 'Web & App Onboarding', 'Merchandise Artwork']
    },
    templates: [
      {
        id: 'ai-1',
        title: 'Custom Brand Mascot Character & Pose Suite',
        companyName: 'Chubby Panda Food Delivery App',
        personName: '6 Character Expressions & Poses',
        jobTitle: 'Friendly Mascot for Web Onboarding, Packaging & Merch | Vector AI/SVG',
        price: '₹1,299.00',
        unitPrice: '₹1,299 (Complete 6-Pose Vector Suite)',
        rating: 4.9,
        reviews: 195,
        image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
        colors: ['#F59E0B', '#EF4444', '#10B981', '#1E293B'],
        orientation: 'Square Vector Artwork',
        corners: 'Complete Character Turnaround Sheet',
        stock: 'Vector EPS / AI Source',
        finish: 'Clean Vector Line & Fill',
        industry: 'Brand Mascot & Character',
        style: '3D Cute Mascot',
        logoArea: 'Center Character Emblem',
        useCase: 'Brand Character Identity',
        badge: 'Bestseller'
      }
    ]
  }
};

export const getAllTemplates = () => {
  const all = [];
  Object.keys(categoryTemplateMap).forEach((slug) => {
    const cat = categoryTemplateMap[slug];
    cat.templates.forEach((t) => {
      all.push({
        ...t,
        categorySlug: slug,
        categoryName: cat.name
      });
    });
  });
  return all;
};
